import { OperatorCatalog } from './query-js';

/**
 * Sample operator catalog (`GET /v1/operators`) for exercising the v2 editor —
 * operators valid per generic type. Ported from the prototype's
 * `EMBEDDED_OPERATORS`. `binary` intentionally has none (unfilterable).
 */
export const operators: OperatorCatalog = [
  {
    type: 'any',
    operators: [
      'equal',
      'greater_than',
      'greater_than_or_equal',
      'less_than',
      'less_than_or_equal',
      'not_equal',
      'is_in',
      'is_not_in',
      'is_empty',
      'is_not_empty',
      'starts_with',
      'ends_with',
      'contains',
      'like',
      'regexp',
      'any_match',
      'all_match',
      'has_key',
      'has_value',
      'is_in_cidr',
      'is_not_in_cidr',
    ],
  },
  { type: 'array', operators: ['contains', 'any_match', 'all_match'] },
  { type: 'binary', operators: [] },
  { type: 'boolean', operators: ['equal', 'not_equal', 'is_empty', 'is_not_empty'] },
  {
    type: 'date',
    operators: [
      'equal',
      'not_equal',
      'greater_than',
      'greater_than_or_equal',
      'less_than',
      'less_than_or_equal',
      'is_in',
      'is_not_in',
      'is_empty',
      'is_not_empty',
    ],
  },
  {
    type: 'enum',
    operators: [
      'equal',
      'not_equal',
      'greater_than',
      'greater_than_or_equal',
      'less_than',
      'less_than_or_equal',
      'is_in',
      'is_not_in',
      'is_empty',
      'is_not_empty',
    ],
  },
  {
    type: 'ip',
    operators: [
      'equal',
      'not_equal',
      'is_in',
      'is_not_in',
      'is_empty',
      'is_not_empty',
      'is_in_cidr',
      'is_not_in_cidr',
    ],
  },
  { type: 'map', operators: ['contains', 'has_key', 'has_value'] },
  {
    type: 'number',
    operators: [
      'equal',
      'not_equal',
      'greater_than',
      'greater_than_or_equal',
      'less_than',
      'less_than_or_equal',
      'is_in',
      'is_not_in',
    ],
  },
  {
    type: 'string',
    operators: [
      'equal',
      'not_equal',
      'greater_than',
      'greater_than_or_equal',
      'less_than',
      'less_than_or_equal',
      'is_in',
      'is_not_in',
      'is_empty',
      'is_not_empty',
      'starts_with',
      'ends_with',
      'contains',
      'like',
      'regexp',
    ],
  },
  { type: 'struct', operators: ['contains'] },
  {
    type: 'timestamp',
    operators: [
      'equal',
      'not_equal',
      'greater_than',
      'greater_than_or_equal',
      'less_than',
      'less_than_or_equal',
      'is_in',
      'is_not_in',
      'is_empty',
      'is_not_empty',
    ],
  },
  { type: 'union', operators: ['contains'] },
  { type: 'uuid', operators: ['equal', 'not_equal', 'is_in', 'is_not_in', 'is_empty', 'is_not_empty'] },
];
